[package]
name = "syngestures"
version = "0.1.0"
authors = ["Mahmoud Al-Qudsi <mqudsi@neosmart.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
regex = { version = "1.3.9" }
serde = { version = "1.0", features = [ "derive" ] }
serde_repr = "0.1"
toml = "0.5.7"
